# Generated by Django 5.1.15 on 2026-03-12 19:31

import apps.importacao_exportacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_importacao', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON'), ('zip', 'ZIP')], max_length=10)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to=apps.importacao_exportacao.models.importacao_upload_path)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('total_sucesso', models.PositiveIntegerField(default=0)),
                ('total_erro', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True, help_text='Log detalhado do processamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lote de Importação',
                'verbose_name_plural': 'Lotes de Importação',
                'ordering': ['-created_at'],
            },
        ),
    ]
