# Generated by Django 5.1.15 on 2026-03-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLiturgica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria Litúrgica',
                'verbose_name_plural': 'Categorias Litúrgicas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('letra', models.TextField(blank=True, help_text='Letra completa da música')),
                ('tom_principal', models.CharField(choices=[('C', 'C (Dó Maior)'), ('Cm', 'Cm (Dó Menor)'), ('C#', 'C# (Dó# Maior)'), ('C#m', 'C#m (Dó# Menor)'), ('D', 'D (Ré Maior)'), ('Dm', 'Dm (Ré Menor)'), ('D#', 'D# (Ré# Maior)'), ('D#m', 'D#m (Ré# Menor)'), ('Eb', 'Eb (Mib Maior)'), ('E', 'E (Mi Maior)'), ('Em', 'Em (Mi Menor)'), ('F', 'F (Fá Maior)'), ('Fm', 'Fm (Fá Menor)'), ('F#', 'F# (Fá# Maior)'), ('F#m', 'F#m (Fá# Menor)'), ('G', 'G (Sol Maior)'), ('Gm', 'Gm (Sol Menor)'), ('G#', 'G# (Sol# Maior)'), ('G#m', 'G#m (Sol# Menor)'), ('Ab', 'Ab (Láb Maior)'), ('A', 'A (Lá Maior)'), ('Am', 'Am (Lá Menor)'), ('Bb', 'Bb (Sib Maior)'), ('Bbm', 'Bbm (Sib Menor)'), ('B', 'B (Si Maior)'), ('Bm', 'Bm (Si Menor)'), ('NI', 'Não Informado')], default='NI', help_text='Tom principal da música', max_length=10)),
                ('tom_normalizado', models.CharField(blank=True, editable=False, help_text='Tom normalizado automaticamente', max_length=10)),
                ('andamento', models.CharField(blank=True, help_text='Ex: Moderado, Rápido, Lento', max_length=50)),
                ('compasso', models.CharField(blank=True, help_text='Ex: 4/4, 3/4, 6/8', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('manual', 'Cadastro Manual'), ('importacao', 'Importação'), ('migracao', 'Migração')], default='manual', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='musicas', to='musicas.categorialiturgica')),
                ('tags', models.ManyToManyField(blank=True, related_name='musicas', to='musicas.tag')),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
                'ordering': ['titulo'],
            },
        ),
    ]
