# Generated by Django 5.1.15 on 2026-03-12 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_celebracao', models.DateField(blank=True, null=True)),
                ('tipo_celebracao', models.CharField(choices=[('missa_dominical', 'Missa Dominical'), ('missa_semanal', 'Missa Semanal'), ('missa_solenidade', 'Missa de Solenidade'), ('adoracao', 'Adoração'), ('retiro', 'Retiro'), ('encontro', 'Encontro'), ('outro', 'Outro')], default='missa_dominical', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repertório',
                'verbose_name_plural': 'Repertórios',
                'ordering': ['-data_celebracao', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepertorioMusica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tom_no_repertorio', models.CharField(blank=True, choices=[('C', 'C (Dó Maior)'), ('Cm', 'Cm (Dó Menor)'), ('C#', 'C# (Dó# Maior)'), ('C#m', 'C#m (Dó# Menor)'), ('D', 'D (Ré Maior)'), ('Dm', 'Dm (Ré Menor)'), ('D#', 'D# (Ré# Maior)'), ('D#m', 'D#m (Ré# Menor)'), ('Eb', 'Eb (Mib Maior)'), ('E', 'E (Mi Maior)'), ('Em', 'Em (Mi Menor)'), ('F', 'F (Fá Maior)'), ('Fm', 'Fm (Fá Menor)'), ('F#', 'F# (Fá# Maior)'), ('F#m', 'F#m (Fá# Menor)'), ('G', 'G (Sol Maior)'), ('Gm', 'Gm (Sol Menor)'), ('G#', 'G# (Sol# Maior)'), ('G#m', 'G#m (Sol# Menor)'), ('Ab', 'Ab (Láb Maior)'), ('A', 'A (Lá Maior)'), ('Am', 'Am (Lá Menor)'), ('Bb', 'Bb (Sib Maior)'), ('Bbm', 'Bbm (Sib Menor)'), ('B', 'B (Si Maior)'), ('Bm', 'Bm (Si Menor)'), ('NI', 'Não Informado')], default='', help_text='Tom específico para esta celebração (se diferente do principal)', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('categoria_no_repertorio', models.ForeignKey(blank=True, help_text='Categoria/momento litúrgico neste repertório', null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicas.categorialiturgica')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertorios', to='musicas.musica')),
                ('repertorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='repertorios.repertorio')),
            ],
            options={
                'verbose_name': 'Música no Repertório',
                'verbose_name_plural': 'Músicas no Repertório',
                'ordering': ['ordem'],
                'unique_together': {('repertorio', 'musica', 'ordem')},
            },
        ),
    ]
