# Generated by Django 5.1.15 on 2026-03-12 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repertorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempoLiturgico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('advento', 'Advento'), ('natal', 'Natal'), ('tempo_comum_1', 'Tempo Comum (1ª Parte)'), ('quaresma', 'Quaresma'), ('tríduo_pascal', 'Tríduo Pascal'), ('pascoa', 'Páscoa'), ('tempo_comum_2', 'Tempo Comum (2ª Parte)')], max_length=30, unique=True)),
                ('cor_liturgica', models.CharField(blank=True, help_text='Ex: verde, roxo, branco, vermelho', max_length=30)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tempo Litúrgico',
                'verbose_name_plural': 'Tempos Litúrgicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Celebracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('tipo_celebracao', models.CharField(choices=[('missa_dominical', 'Missa Dominical'), ('missa_semanal', 'Missa Semanal'), ('missa_solenidade', 'Missa de Solenidade'), ('adoracao', 'Adoração'), ('retiro', 'Retiro'), ('encontro', 'Encontro'), ('outro', 'Outro')], default='missa_dominical', max_length=30)),
                ('local', models.CharField(blank=True, max_length=255)),
                ('celebrante', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repertorio', models.ForeignKey(blank=True, help_text='Repertório vinculado a esta celebração', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebracoes', to='repertorios.repertorio')),
                ('tempo_liturgico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebracoes', to='agenda.tempoliturgico')),
            ],
            options={
                'verbose_name': 'Celebração',
                'verbose_name_plural': 'Celebrações',
                'ordering': ['data', 'horario'],
            },
        ),
    ]
