# Generated by Django 5.1.15 on 2026-03-12 19:31

import apps.arquivos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioProprio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to=apps.arquivos.models.audio_upload_path)),
                ('tipo', models.CharField(choices=[('ensaio', 'Ensaio'), ('voz_violao', 'Voz e Violão'), ('coral', 'Coral'), ('instrumental', 'Instrumental'), ('playback', 'Playback'), ('referencia', 'Referência Interna')], default='ensaio', max_length=20)),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('formato', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='musicas.musica')),
            ],
            options={
                'verbose_name': 'Audio Proprio',
                'verbose_name_plural': 'Audios Proprios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cifra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cifra', models.CharField(choices=[('texto', 'Texto Digitado'), ('pdf', 'PDF'), ('link', 'Link Externo')], default='texto', max_length=10)),
                ('conteudo_texto', models.TextField(blank=True, help_text='Conteudo da cifra em texto')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to=apps.arquivos.models.cifra_upload_path)),
                ('link_referencia', models.URLField(blank=True, max_length=500)),
                ('tom', models.CharField(blank=True, choices=[('C', 'C (Dó Maior)'), ('Cm', 'Cm (Dó Menor)'), ('C#', 'C# (Dó# Maior)'), ('C#m', 'C#m (Dó# Menor)'), ('D', 'D (Ré Maior)'), ('Dm', 'Dm (Ré Menor)'), ('D#', 'D# (Ré# Maior)'), ('D#m', 'D#m (Ré# Menor)'), ('Eb', 'Eb (Mib Maior)'), ('E', 'E (Mi Maior)'), ('Em', 'Em (Mi Menor)'), ('F', 'F (Fá Maior)'), ('Fm', 'Fm (Fá Menor)'), ('F#', 'F# (Fá# Maior)'), ('F#m', 'F#m (Fá# Menor)'), ('G', 'G (Sol Maior)'), ('Gm', 'Gm (Sol Menor)'), ('G#', 'G# (Sol# Maior)'), ('G#m', 'G#m (Sol# Menor)'), ('Ab', 'Ab (Láb Maior)'), ('A', 'A (Lá Maior)'), ('Am', 'Am (Lá Menor)'), ('Bb', 'Bb (Sib Maior)'), ('Bbm', 'Bbm (Sib Menor)'), ('B', 'B (Si Maior)'), ('Bm', 'Bm (Si Menor)'), ('NI', 'Não Informado')], default='', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cifras', to='musicas.musica')),
            ],
            options={
                'verbose_name': 'Cifra',
                'verbose_name_plural': 'Cifras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('youtube', 'YouTube'), ('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('site_externo', 'Site Externo'), ('generico', 'Link Genérico')], default='generico', max_length=20)),
                ('tipo_conteudo', models.CharField(choices=[('video', 'Vídeo'), ('audio', 'Áudio'), ('cifra', 'Cifra'), ('letra', 'Letra'), ('referencia', 'Referência')], default='referencia', max_length=20)),
                ('titulo_externo', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('embed_url', models.URLField(blank=True, max_length=500)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_externos', to='musicas.musica')),
            ],
            options={
                'verbose_name': 'Link Externo',
                'verbose_name_plural': 'Links Externos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo do arquivo', max_length=255)),
                ('arquivo', models.FileField(upload_to=apps.arquivos.models.pdf_upload_path)),
                ('tamanho_bytes', models.PositiveIntegerField(default=0, editable=False)),
                ('pagina_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('pagina_final', models.PositiveIntegerField(blank=True, null=True)),
                ('texto_extraido', models.TextField(blank=True, help_text='Texto extraido automaticamente do PDF (pode conter erros)')),
                ('origem', models.CharField(blank=True, default='upload', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='musicas.musica')),
            ],
            options={
                'verbose_name': 'PDF',
                'verbose_name_plural': 'PDFs',
                'ordering': ['-created_at'],
            },
        ),
    ]
